"""add users and user types

Revision ID: 38489f87dcae
Revises: 5b385e2d8f5a
Create Date: 2026-09-09 23:56:48.813534
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "38489f87dcae"
down_revision: str | None = "5b385e2d8f5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_types",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("selectable_on_registration", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_user_types_code"), "user_types", ["code"], unique=True)
    op.create_index(op.f("ix_user_types_is_active"), "user_types", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("system_role", sa.Enum("ADMIN", "USER", name="systemrole"), nullable=False),
        sa.Column("user_type_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["user_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_system_role"), "users", ["system_role"], unique=False)
    op.create_index(op.f("ix_users_user_type_id"), "users", ["user_type_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_user_type_id"), table_name="users")
    op.drop_index(op.f("ix_users_system_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_types_is_active"), table_name="user_types")
    op.drop_index(op.f("ix_user_types_code"), table_name="user_types")
    op.drop_table("user_types")
    # ### end Alembic commands ###
